### ISSUE TITLE
when python main.py, show this error 

### ISSUE THREAD

**Issue by xiaol** [hizkifw/WebChatRWKVstic#1]
![image](https://user-images.githubusercontent.com/1669515/219823670-b1ee5cd9-ac93-43d3-8b1a-3a761acb66cb.png)

do you have any instructions about enviroments install?
Thank you

**Comment by hizkifw** [comment]
Can you try some of the workarounds in this post? https://stackoverflow.com/a/74828501

**Comment by xiaol** [comment]
yes，uninstall clubalas fix  the problems

Hizkia Felix ***@***.***> 于 2023年2月18日周六 11:15写道：
