### ISSUE TITLE
how to use  args.strategy = 'cuda fp16i8 *15+' to  run 7b model on rtx2060 6G 

### ISSUE THREAD

**Issue by amberfay** [hizkifw/WebChatRWKVstic#6]
i can use args.strategy = 'cuda fp16i8 *15+'  run 7b model on rtx2060 6G 

while use this webchat , i could't find  how to set args.strategy

does it not support or i did'nt find it

**Comment by amberfay** [comment]
now the vram not enough

**Comment by hizkifw** [comment]
I'm not sure how to configure all the different parameters for the model, but you can modify the `model.py` file here.

https://github.com/hizkifw/WebChatRWKVstic/blob/48e76ddc3d826a81f7328305eb95b6c368056db6/model.py#L173-L179

I'm using `rwkvstic` so you can check their repo for more info. https://github.com/harrisonvanderbyl/rwkvstic
